#include "FortContextualTutorial_AbilityActivatedInformative.h"

void UFortContextualTutorial_AbilityActivatedInformative::HandleStartSkydivingForActivation() {
}

UFortContextualTutorial_AbilityActivatedInformative::UFortContextualTutorial_AbilityActivatedInformative() {
}
