#pragma once
#include "CoreMinimal.h"
#include "EMatchmakingErrorV2.generated.h"

UENUM()
enum class EMatchmakingErrorV2 : int32 {
    Success,
    Canceled,
    NeedUpdate,
    VersionMismatch,
    UpdateFailed,
    NotLoggedIn,
    NoIdentityInterface,
    NoSessionInterface,
    AlreadyInSession,
    FindSessionFailure,
    InvalidSessionId,
    FailedToQueryEncryptionKey,
    FailedToRefreshAuthToken,
    FailedToCleanupSession,
    FailedToJoinSession,
    FailedToTravelToSession,
    Unauthorized,
    BannedFromAthena,
    BannedFromAthenaForExploit,
    BannedFromAthenaForTeaming,
    BannedFromAthenaForTeamKilling,
    InvalidCustomMatchKey,
    FailedToContactGameServices,
    FailedToConnectToMMS,
    MMSCommunicationIssue,
    ServiceReturnedError,
    PlaylistNoLongerAvailable,
    CrossplayUnsetWithInputDevicePoolShift,
    CrossplayNeededForTournamentMatch,
    MatchmakingDisabled,
    AccountLevelTooLow,
    JoinInProgressError,
    SpectateInProgressError,
    MatchmakingInProgress,
    TooFrequentRequests,
    FailedToAcquireContent,
    CellularDataRefusal,
    CancelledDownloadContent,
    DataAssetDirectoryUpdateFailed,
    InvalidPlaylistRevision,
    UnknownError,
};

